### PR TITLE
Update Ryan.tsx

### PR DESCRIPTION
**Pull request by stwater20**
update bio

by the way,
how to add a href link in the text?

### CODE REVIEW

**Comment by ntut-xuan** [comment]
It may valid to add HTML DOM into bio like this. It can support in the future.

```tsx
bio={<p>Hi I'm <a href="www.google.com">Xuan</a></p>}
```

**Comment by stwater20** [comment]
OK! thank you.

I have removed html tag from bio.

**Comment by ntut-xuan** [comment]
Hi, I already add the feature you request on #22, please check the changes to know how to add element on your bio, thanks!

**Comment by ntut-xuan** [comment]
The author said it will modify the bio in the future, so I merge the branch.

**Pull request merged**
